<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[---Database Connection Established---]]>
    </line>
    <line>
      <![CDATA[Browser got Launched Sucessfully]]>
    </line>
    <line>
      <![CDATA[Navigated to Vtiger HomePage Sucessfully]]>
    </line>
    <line>
      <![CDATA[Logged out Successfully]]>
    </line>
    <line>
      <![CDATA[Browser got closed Successfully]]>
    </line>
    <line>
      <![CDATA[---Database Disconnected Sucessfully---]]>
    </line>
  </reporter-output>
  <suite started-at="2025-04-04T10:27:15 IST" name="Default suite" finished-at="2025-04-04T10:27:54 IST" duration-ms="39048">
    <groups>
    </groups>
    <test started-at="2025-04-04T10:27:15 IST" name="Default test" finished-at="2025-04-04T10:27:54 IST" duration-ms="39048">
      <class name="contactTest.ToCreateContactWithOrgTest">
        <test-method is-config="true" signature="bsConfig()[pri:0, instance:contactTest.ToCreateContactWithOrgTest@6069db50]" started-at="2025-04-04T10:27:15 IST" name="bsConfig" finished-at="2025-04-04T10:27:15 IST" duration-ms="16" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[---Database Connection Established---]]>
            </line>
          </reporter-output>
        </test-method> <!-- bsConfig -->
        <test-method is-config="true" signature="bcConfig()[pri:0, instance:contactTest.ToCreateContactWithOrgTest@6069db50]" started-at="2025-04-04T10:27:15 IST" name="bcConfig" finished-at="2025-04-04T10:27:22 IST" duration-ms="6857" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser got Launched Sucessfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- bcConfig -->
        <test-method is-config="true" signature="bmConfig()[pri:0, instance:contactTest.ToCreateContactWithOrgTest@6069db50]" started-at="2025-04-04T10:27:22 IST" name="bmConfig" finished-at="2025-04-04T10:27:23 IST" duration-ms="573" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Navigated to Vtiger HomePage Sucessfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- bmConfig -->
        <test-method signature="ToCreateContactWithOrgTest__005()[pri:0, instance:contactTest.ToCreateContactWithOrgTest@6069db50]" started-at="2025-04-04T10:27:23 IST" name="ToCreateContactWithOrgTest__005" finished-at="2025-04-04T10:27:50 IST" duration-ms="26929" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at contactTest.ToCreateContactWithOrgTest.ToCreateContactWithOrgTest__005(ToCreateContactWithOrgTest.java:39)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ToCreateContactWithOrgTest__005 -->
        <test-method is-config="true" signature="amConfig()[pri:0, instance:contactTest.ToCreateContactWithOrgTest@6069db50]" started-at="2025-04-04T10:27:50 IST" name="amConfig" finished-at="2025-04-04T10:27:53 IST" duration-ms="3377" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Logged out Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- amConfig -->
        <test-method is-config="true" signature="acConfig()[pri:0, instance:contactTest.ToCreateContactWithOrgTest@6069db50]" started-at="2025-04-04T10:27:53 IST" name="acConfig" finished-at="2025-04-04T10:27:54 IST" duration-ms="464" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[Browser got closed Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- acConfig -->
        <test-method is-config="true" signature="asConfig()[pri:0, instance:contactTest.ToCreateContactWithOrgTest@6069db50]" started-at="2025-04-04T10:27:55 IST" name="asConfig" finished-at="2025-04-04T10:27:55 IST" duration-ms="0" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[---Database Disconnected Sucessfully---]]>
            </line>
          </reporter-output>
        </test-method> <!-- asConfig -->
      </class> <!-- contactTest.ToCreateContactWithOrgTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
